# Generated by Django 5.0.6 on 2024-05-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramchat',
            old_name='time_zone',
            new_name='timezone',
        ),
    ]
