# Generated by Django 5.0.6 on 2024-05-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_time_zone_telegramchat_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchat',
            name='timezone',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
