version: "3.9"

services:
  redis:
    image: redis
    restart: always
  
  app:
    restart: always
    build: 
      context: ./src
    ports: 
      - "8000:8000"
    command: ["python3", "./app/manage.py", "runserver", "0.0.0.0:8000"]

  bot:
    restart: always
    build: 
      context: ./src
    command: ["python3", "./app/manage.py", "bot"]

  
  worker:
    restart: always
    build: 
      context: ./src
    command: ['celery', '--workdir=./app', '-A', 'app', 'worker', '-B' ]