version: "3.9"

services:
  redis:
    image: redis
    restart: always
  
  app:
    restart: always
    build: 
      context: ./src
    ports: 
      - "8000:8000"
    command: [ "run.sh"]
  
  # worker:
  #   restart: always
  #   build: 
  #     context: ./webapp
  #   volumes: 
  #     - ./cats:/app/src/cats
  #   command: ['celery', '--workdir=./src', '-A', 'proj', 'worker' ]